# Generated by Django 4.0.5 on 2022-06-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('_id', models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(db_index=True, max_length=450)),
                ('type', models.CharField(choices=[('plain', 'Plain'), ('meter', 'Meter')], db_index=True, default='plain', max_length=5)),
                ('availability', models.BooleanField(default=True)),
                ('needing_repair', models.BooleanField(default=False)),
                ('durability', models.PositiveIntegerField(default=0)),
                ('max_durability', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('minimum_rent_period', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
    ]
