# Generated by Django 4.0.5 on 2022-06-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_alter_product_mileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rent_expire_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rented_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
